<a href="https://colab.research.google.com/github/abidhasanfahim/ML_Python/blob/main/ML_and_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
list1 = [1,2,3,4,5]
list2 = [1, "abid", True, False, 5]
print(list1)
print(list2) #lists are inefficient as they can take multiple variable and mutable
#That's why we are going to use numpy array

[1, 2, 3, 4, 5]
[1, 'abid', True, False, 5]


#NumPy Arrays

In [8]:
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.arange(0,10,2)
a3 = np.linspace(1,10,2)
print(a1, a2, a3)
print(type(a2))

[1 2 3 4 5] [0 2 4 6 8] [ 1. 10.]
<class 'numpy.ndarray'>


In [35]:
a3 = np.zeros(5)  #creates an array of zeros
#print(a3)
#a4 = np.ones(5)   #creates an array of ones
#print(a4)
#a5 = np.random.randint(1,100,10)
#print(a5)
a6 = np.eye(5)
print(a6)
a7 =  np.random.random((2,4))  #np.random is the module and random() is the function
print(a7)
print(a7.shape)
print(a7.dtype)
print(a7[1,2])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.72969305 0.73977482 0.30644558 0.81734   ]
 [0.14728293 0.99145807 0.58152949 0.63010365]]
(2, 4)
float64
0.5815294924519714


In [45]:
list1= [1,2,3,4,5]
r1 = np.array(list1)
print(r1)
print(r1.shape)
print(r1.dtype)
list2 = [1, "abid", True, False, 5]
r2 =  np.array ([list1, list2])
print(r2)
print(r2.shape)
print(r2.dtype)
print(r1[r1>2])
nums = np.arange(10)
print(nums)
print(nums[nums>5])

[1 2 3 4 5]
(5,)
int64
[['1' '2' '3' '4' '5']
 ['1' 'abid' 'True' 'False' '5']]
(2, 5)
<U21
[3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
